### ISSUE TITLE
[Question] how to use multiple pub topics

### ISSUE THREAD

**Issue by wybelution** [ethanhjennings/MQTTSerialPrinter#1]
the simplicity of the library is a strong chracteristic :-). Currently the publish topic is set during initialization of the class instance. What is the best way to use more than 1 publish topic in the current implementation of MQTTSerialPrinter? Use a second instance? Or would such functionality require an update of the MQTTSerialPrinter code?

**Comment by ethanhjennings** [comment]
Thank you! Yeah, the easiest way would be to just have multiple printer instances sharing the same mqtt client. That would work fine if you want to send some messages to one topic and some to another like this:

```C++
WiFiClient wifi_client;
PubSubClient mqtt_client(wifi_client);

MQTTSerialPrinter Log1(mqtt_client, "topic_1");
MQTTSerialPrinter Log2(mqtt_client, "topic_2");

...

// Send to topic_1
Log1.println("Hello topic 1");

// Send to topic_2
Log2.println("Hello topic 2");

```


If you want it to repeat the same message to a bunch of topics it would be cleaner with a change to MQTTSerialPrinter. Instead of a single topic it could store an array and have an addTopic() function maybe. If that's something you want feel free to re-open this issue and I can add it or feel free to open your own PR!
